import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Saira } from "next/font/google";
import "./globals.css";
import { TanstackProviders } from "@/components/tanstackprovider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Dashboard from "@/components/Dashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${saira.variable}  ${roboto.variable}  antialiased`}
      >
        <TanstackProviders>
          <Navbar />
          <Dashboard />
          {children}
          <Footer />
        </TanstackProviders>
      </body>
    </html>
  );
}
